US8.1 card synthétique
WildCodeSchool/nts-js-202009-p2-culture pull request #12
Opened 2020-10-29 12:57 UTC by loicbdev

J'ai fait une "première" version responsive de la card synthétique d'un évèvement. Eslint n'est pas ok pour les span mais c'est focntionnel. Là non plus, je n'ai pas (encore) intégré le CSS avec Style-component... Cette card ne reprend donc que les infos essentielles et renverra vers la card détaillée.

2020-10-29 14:33 UTC, bastienwcs requested changes

2020-10-29 14:33 UTC, bastienwcs commented on src/components/SyntheticCard.css
> +  }
espaces à supprimer, utiliser CTL+MAJ+I

2020-10-30 08:58 UTC, bastienwcs approved these changes

2020-10-30 09:12 UTC, loicbdev commented
Conflict resolve!

2020-10-30 09:12 UTC, loicbdev commented
conflict resolved!

2020-10-30 09:12 UTC, merged